### ISSUE TITLE
unmatched user can unmatch

### ISSUE THREAD

**Issue by wjycn2000** [Harmandeepsinghteja/Lifelong#27]
browser shows "Unmatched successfully" message

**Comment by wjycn2000** [comment]
We can disable "unmatch" button.

**Comment by Harmandeepsinghteja** [comment]
@wjycn2000 I didn't understand the issue. Can you please elaborate ?

**Comment by wjycn2000** [comment]
A user who is not matched can click on unmatch and the website show dialog saying unmatched successfully.
![image](https://github.com/user-attachments/assets/7aa0b6dd-8388-4de2-8370-18f0f34e8fc0)

**Comment by wjycn2000** [comment]
I don't know if it is fixed or not. Maybe I'm behind version
